### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by juliohm** [scuervo91/WellLogs.jl#1]
Hi @scuervo91 , thank you again for the effort. I would like to contribute and improve the integration with other packages.

Before we proceed, could you please add a LICENSE file to the root folder? If you don't have any particular preference for a license, I suggest the [ISC license](https://en.wikipedia.org/wiki/ISC_license), which is equivalent to MIT, but uses a more succinct language. Most Julia packages use the MIT license.

**Comment by juliohm** [comment]
@scuervo91 did you have a chance to look into this?

**Comment by scuervo91** [comment]
Hi @juliohm. I'm confused. This is the licence file, isn't it?

![LICENSEwl](https://user-images.githubusercontent.com/47048845/60111594-d853af00-9733-11e9-8c9b-ac07b2502475.PNG)

**Comment by juliohm** [comment]
Yes, I don't know why I missed it. Closing the issue.
